spring.application.name=spring-and-spring-boot
spring.main.banner-mode=off

### server configuration
server.port=8080

### configure task-scheduling
spring.task.scheduling.pool.size=5

### user defined properties
user.my-name=fpolizzi

app.stripe.api-key=foobar-prod-1p2o3i4
app.stripe.url=https://prod.api.stripe.com