spring.application.name=spring-and-spring-boot

### show web-related error messages
#spring.web.error.include-message=always
###
#spring.web.error.include-binding-errors=always

### Change tomcat server port
# server.port=8585

### h2 - settings
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:amigoscode
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

### Load data.sql into the database
#spring.jpa.defer-datasource-initialization=true
