spring.application.name=spring-and-spring-boot
spring.main.banner-mode=console

### server configuration
server.port=8080

### show web-related error messages
#spring.web.error.include-message=always
###
#spring.web.error.include-binding-errors=always

### Change tomcat server port
# server.port=8585

### h2 - settings
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:amigoscode
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

### Load data.sql into the database
#spring.jpa.defer-datasource-initialization=true

### configure task-scheduling
# spring.task.scheduling.pool.size=5

### user defined properties
user.my-name=fpolizzi

app.stripe.api-key=foobar
app.stripe.url=https://api.stripe.com

### configure task-scheduling
#spring.task.scheduling.pool.size=5

### configure logging
logging.level.root=info
logging.level.sql=debug
logging.level.org.springframework.web=debug
logging.level.com.fpolizzi=info